version: '3.4'

services:
  scoredataservice:
    image: ${DOCKER_REGISTRY-}scoredataservice
    build:
      context: .
      dockerfile: ScoreDataService/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
  sudentdataservice:
    image: ${DOCKER_REGISTRY-}studentdataservice
    build:
        context: .
        dockerfile: StudentDataService/Dockerfile
    ports:
      - "5002:80"
      - "5003:443"