version: '3.4'

services:
  scoredataservice:
    image: ${DOCKER_REGISTRY-}scoredataservice
    build:
      context: .
      dockerfile: ScoreDataService/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
  sudentdataservice:
    image: ${DOCKER_REGISTRY-}studentdataservice
    build:
        context: .
        dockerfile: StudentDataService/Dockerfile
    ports:
      - "8082:80"
      - "8083:443"